# Site settings
title: kevinreedy.net
email: kevinreedy@gmail.com
description: >
  Bits.
  Beats.
  Things that start with 'B' for $800.
baseurl: ""
url: "http://kevinreedy.net" # the base hostname & protocol for your site
twitter_username: kevinreedy
github_username:  kevinreedy

# Build settings
markdown: kramdown
