# Site settings
title: kevinreedy.net
author: Kevin Reedy
email: kevinreedy@gmail.com
meta_description: >
  Homepage of Kevin Reedy, Founder of RecRec, from Chicago, IL.
  He has a love/hate relationship with the word DevOps.
  In his free time, he enjoys Playing Shuffleboard, Cycling, Cooking, Brewing Beer, and promising himself that he'll update his Blog more often.
baseurl: ""
url: "https://kevinreedy.net" # the base hostname & protocol for your site
twitter_username: kevinreedy
github_username: kevinreedy
linkedin_username: kevinreedy
mastodon_username: "@kevinreedy@hachyderm.io"
mastodon_profile: https://hachyderm.io/@kevinreedy

plugins:
  - jekyll-sitemap

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - s3_website.yml
  - vendor
